<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\UIFramework.Core\UIFramework.Core.csproj" />
    <ProjectReference Include="..\UIFramework.Controls\UIFramework.Controls.csproj" />
    <ProjectReference Include="..\UIFramework.Grid\UIFramework.Grid.csproj" />
  </ItemGroup>
</Project>
